### ISSUE TITLE
update instructions with how to install hypervisor 

### ISSUE THREAD

**Issue by ibenrodriguez** [buzaturadu/stuff#1]
Please update the instructions with how to install hypervisor and get iso... here are the steps I had to follow.

- sudo su 
- lsb_release -a

Description:	Pop!_OS 20.04 LTS

- apt install -y virt-manager qemu-efi
- wget https://nyifiles.pfsense.org/mirror/downloads/pfSense-CE-2.4.5-RELEASE-p1-amd64.iso.gz
- gunzip pfSense-CE-2.4.5-RELEASE-p1-amd64.iso.gz 

And I'm getting this error when trying to follow these steps... any suggestions?

`admin@pop-os:~$ cd /opt`
`admin@pop-os:/opt$ sudo virt-install --name pfsense --ram 2048 --disk path=pfsense.qcow2,size=10 --vcpus 1 --os-type linux --os-variant generic --network bridge=virbr0 --network bridge=virbr1 --network bridge=virbr2 --graphics vnc --console pty,target_type=serial --cdrom 'pfSense-CE-2.4.5-RELEASE-p1-amd64.iso'`
WARNING  Graphics requested but DISPLAY is not set. Not running virt-viewer.
WARNING  No console to launch for the guest, defaulting to --wait -1

Starting install...
Allocating 'pfsense.qcow2'                                                                                                                                                                 |  10 GB  00:00:00     
ERROR    Cannot get interface MTU on 'virbr1': No such device
Removing disk 'pfsense.qcow2'                                                                                                                                                              |    0 B  00:00:00     
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start pfsense
otherwise, please restart your installation.
admin@pop-os:/opt$

**Comment by buzaturadu** [comment]
The problem with creating the VM it's because the networking setup its not good in your environment , virbr1 it's missing and probably also the other bridges. I'll update the repo so it will include this steps also
